dist: bionic
language: c
jobs:
  include:
  - env: configure_args=''
  - env: configure_args='--enable-cassert'
  - env: configure_args='--enable-cassert --with-uregex'
  - env: configure_args='CPPFLAGS=-DUSE_SYSTEMD LIBS=-lsystemd'
  - compiler: clang
  - dist: trusty
  - dist: xenial
  - dist: focal
  - arch: arm64
  - arch: ppc64le
before_install: |
  set -e
  sudo apt-get update
install: |
  set -e
  pkgs="libevent-dev"
  case $configure_args in *USE_SYSTEMD*) pkgs="$pkgs libsystemd-dev";; esac
  sudo apt-get -y install $pkgs
script: |
  set -e
  ./autogen.sh
  ./configure --prefix=$HOME/install --enable-werror $configure_args
  make
  make check
  make install
